local Instrument = Musician.MIDI_INSTRUMENTS

Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Ocarina] = "ocarina"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Glockenspiel] = "glockenspiel"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Banjo] = "banjo"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Shamisen] = "sheikharp"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Lead6Voice] = "choirmale"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Pad4Choir] = "choirfemale"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.ReedOrgan] = "ganonorgan"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Harpsichord] = "harpsichord"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Vibraphone] = "varimba"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.Piccolo] = "piccolo"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.PizzicatoStrings] = "pizzicatostrings"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.StringEnsemble1] = "strings"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.BaritoneSax] = "sassoon"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.SynthBrass1] = "frenchhorn"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.TangoAccordion] = "taccordion"
Musician.MIDI_INSTRUMENT_MAPPING[Instrument.PanFlute] = "panflute"